In [1]:
import sys
sys.path.insert(0, '../src')
import pandas as pd

In [2]:
df = pd.read_csv("../data/absortion.csv")
df

                id  target                                           sequence
0   sequence_40826     539  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
1   sequence_40787     510  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
2   sequence_40789     510  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
3   sequence_40794     519  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
4   sequence_40806     525  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
..             ...     ...                                                ...
76  sequence_40795     562  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
77  sequence_40866     620  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
78  sequence_40799     597  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
79  sequence_40788     510  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
80  sequence_40867     622  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...

[81 rows x 3 columns]

## One Hot encoding

In [3]:
from numerical_representation.one_hot_encoding import OneHotEncoding

In [4]:
one_hot_encoding = OneHotEncoding(df, "id", "sequence")
df_result = one_hot_encoding.encode_dataset()
df_result

,id,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_5950,p_5951,p_5952,p_5953,p_5954,p_5955,p_5956,p_5957,p_5958,p_5959
0,sequence_40826,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,sequence_40787,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,sequence_40789,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,sequence_40794,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,sequence_40806,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,sequence_40795,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
77,sequence_40866,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
78,sequence_40799,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
79,sequence_40788,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
80,sequence_40867,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

## Physicochemical properties

In [5]:
from numerical_representation.physicochemical_properties import Physicochemical

In [6]:

physicochemical = Physicochemical(df, "Group_0", "../input_encoders/clustering_encoders.csv", "sequence", "id")
df_result = physicochemical.encode_dataset()
df_result

,id,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_288,p_289,p_290,p_291,p_292,p_293,p_294,p_295,p_296,p_297
0,sequence_40826,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
1,sequence_40787,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
2,sequence_40789,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
3,sequence_40794,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
4,sequence_40806,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,sequence_40795,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
77,sequence_40866,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
78,sequence_40799,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
79,sequence_40788,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
80,sequence_40867,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739

## Fast Fourier Transform

In [7]:
from numerical_representation.fft_encoding import FftEncoding

In [8]:
fft = FftEncoding(df_result, "id")
df_result = fft.encoding_dataset()
df_result

,id,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_246,p_247,p_248,p_249,p_250,p_251,p_252,p_253,p_254,p_255
0,sequence_40826,2736.229386,2359.936161,1228.800947,4263.736493,2194.451945,3959.349233,1924.084847,4746.306998,4385.199071,...,3590.102111,1400.527279,1652.193413,389.001970,3542.407648,2726.943012,3534.841922,3144.421280,4020.653668,6899.663280
1,sequence_40787,3144.790735,2635.615599,1472.613044,4526.111685,2594.117124,3747.609912,1747.520864,5066.566095,4529.818633,...,3622.370481,1091.247712,2003.052658,793.433404,3258.709209,2469.443654,3230.232936,2742.602825,4303.762333,7299.192512
2,sequence_40789,2749.888763,2368.532739,1235.547566,4272.137512,2207.761277,3951.771030,1917.038014,4756.795581,4389.496703,...,3590.434520,1389.358606,1663.498073,402.388473,3532.527458,2717.735948,3524.318105,3130.959139,4029.770901,6913.003628
3,sequence_40794,3026.961360,2552.456813,1394.410602,4448.180477,2478.555756,3805.384955,1790.680004,4972.875363,4484.770800,...,3608.350077,1174.232627,1899.498873,676.285844,3337.871827,2539.644545,3315.788911,2858.291383,4220.004197,7183.863752
4,sequence_40806,2875.883204,2455.029289,1291.275376,4334.094693,2334.041747,3914.442737,1894.293852,4877.607408,4477.616240,...,3529.249945,1263.078065,1789.133796,527.650411,3475.697437,2663.302693,3412.504742,3004.804498,4124.575546,7037.397047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,sequence_40795,3124.596058,2658.837698,1216.102580,4377.316366,2442.787032,3781.871907,1949.166889,4965.589546,4437.656466,...,3719.256390,1714.510984,1282.273731,128.077078,3718.389402,2752.243594,3813.820927,3523.044430,3848.779921,6731.844399
77,sequence_40866,2556.570211,2241.643343,1390.206747,4053.438776,2020.665986,3696.373027,1945.782573,4913.712417,4283.251007,...,3523.812661,1536.014520,1269.427133,288.808746,3463.497371,2501.438680,3879.302879,3259.506382,4153.470136,6777.302850
78,sequence_40799,2375.495907,2015.840728,1748.769039,4504.102196,2505.069188,3680.208554,2208.547454,5043.009961,4252.253177,...,3161.550265,1297.612565,1415.190525,228.110790,3374.809340,2693.646323,4271.803471,3636.865707,4313.418927,6906.413549
79,sequence_40788,2729.694086,2366.236437,1517.002473,4172.794197,2187.748988,3596.448393,1881.800429,5032.072237,4321.070701,...,3498.800931,1627.303528,1160.183346,249.986445,3574.226707,2616.178802,3990.866794,3404.084569,4057.491510,6634.239462
80,sequence_40867,2216.031408,1901.122570,1649.307771,4393.761262,2349.870326,3761.013886,2260.256299,4943.094470,4231.188325,...,3189.442106,1199.482727,1549.737455,387.517318,3246.562214,2556.869069,4144.110731,3477.607948,4412.204431,7062.016254

## Protein Language Models

In [9]:
from numerical_representation.protein_language_model import UsingBioembeddings

/home/gabriel/anaconda3/envs/clustering_protein_seqs/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [10]:
using_bioembedding_instance = UsingBioembeddings(df, 'id', 'sequence')

In [11]:
df_fasttext = using_bioembedding_instance.apply_fasttext()
df_fasttext

Reducing embeddings: 81it [00:00, 2069.26it/s]

,id,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_502,p_503,p_504,p_505,p_506,p_507,p_508,p_509,p_510,p_511
0,sequence_40826,-0.049314,-0.133964,-0.004795,-0.095792,0.113773,0.020104,-0.005592,-0.044131,-0.045067,...,-0.028307,0.059830,-0.026787,-0.025275,0.006416,0.043157,0.082496,0.021582,0.054099,-0.043100
1,sequence_40787,-0.048908,-0.134550,-0.004895,-0.096038,0.113516,0.020293,-0.005636,-0.043901,-0.044939,...,-0.028628,0.059456,-0.027088,-0.025318,0.006686,0.043009,0.082666,0.021427,0.054031,-0.042769
2,sequence_40789,-0.049107,-0.134501,-0.004996,-0.096284,0.113369,0.020328,-0.005538,-0.043932,-0.044602,...,-0.028150,0.059537,-0.027145,-0.025236,0.006503,0.043224,0.082458,0.021564,0.054196,-0.042612
3,sequence_40794,-0.049190,-0.134337,-0.005001,-0.095598,0.113241,0.020636,-0.005506,-0.044014,-0.044647,...,-0.028953,0.059454,-0.027321,-0.025582,0.006863,0.043144,0.082564,0.021694,0.054147,-0.042856
4,sequence_40806,-0.049312,-0.133949,-0.004654,-0.095679,0.113494,0.020241,-0.005463,-0.044026,-0.044794,...,-0.027931,0.059438,-0.027060,-0.025542,0.006524,0.043124,0.082730,0.022006,0.054027,-0.042916
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,sequence_40795,-0.048476,-0.133325,-0.003598,-0.094950,0.113772,0.020302,-0.004920,-0.044530,-0.045373,...,-0.029021,0.060458,-0.027323,-0.026220,0.006796,0.043156,0.082255,0.022134,0.054125,-0.042827
77,sequence_40866,-0.048304,-0.134238,-0.003891,-0.095650,0.113730,0.021343,-0.004911,-0.044539,-0.044236,...,-0.028669,0.060589,-0.027940,-0.025872,0.007137,0.043760,0.081399,0.021129,0.054419,-0.043054
78,sequence_40799,-0.048953,-0.133446,-0.004211,-0.095425,0.113553,0.021687,-0.005306,-0.045117,-0.045397,...,-0.028285,0.060758,-0.028303,-0.026009,0.007060,0.044198,0.082339,0.021824,0.054614,-0.042910
79,sequence_40788,-0.048315,-0.134084,-0.004039,-0.096010,0.113125,0.021614,-0.005186,-0.044361,-0.044449,...,-0.028466,0.060699,-0.028191,-0.025889,0.006820,0.043835,0.081663,0.021465,0.053974,-0.042521
80,sequence_40867,-0.048736,-0.134136,-0.004264,-0.095557,0.113755,0.021640,-0.004977,-0.045096,-0.044720,...,-0.028330,0.060356,-0.028409,-0.025954,0.007464,0.044190,0.082036,0.021469,0.055156,-0.042955

In [12]:
df_word2vec = using_bioembedding_instance.apply_word2vec()
df_word2vec

Reducing embeddings: 81it [00:00, 2070.63it/s]

,id,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_502,p_503,p_504,p_505,p_506,p_507,p_508,p_509,p_510,p_511
0,sequence_40826,-0.035338,-0.016951,0.009919,-0.047659,-0.086391,-0.026774,0.056912,-0.009351,-0.019750,...,0.014860,-0.017172,0.069749,-0.043282,-0.061281,-0.034537,-0.019786,-0.063887,0.045605,-0.051987
1,sequence_40787,-0.035174,-0.016634,0.010052,-0.047513,-0.086299,-0.026838,0.057071,-0.009169,-0.019811,...,0.014627,-0.017160,0.069767,-0.042710,-0.061277,-0.034468,-0.019948,-0.064207,0.045421,-0.051741
2,sequence_40789,-0.035305,-0.017034,0.010116,-0.047537,-0.086486,-0.026736,0.057170,-0.009100,-0.019726,...,0.014555,-0.016931,0.069572,-0.043195,-0.061285,-0.034519,-0.020083,-0.064127,0.045277,-0.051621
3,sequence_40794,-0.035309,-0.016975,0.010058,-0.047341,-0.086278,-0.026939,0.057114,-0.009013,-0.019852,...,0.014740,-0.016972,0.069588,-0.043097,-0.061502,-0.034619,-0.019860,-0.064013,0.045126,-0.052000
4,sequence_40806,-0.035398,-0.016742,0.009747,-0.047483,-0.086516,-0.026876,0.056633,-0.009114,-0.019696,...,0.014719,-0.017379,0.069750,-0.043182,-0.060975,-0.034730,-0.019376,-0.063835,0.045802,-0.052053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,sequence_40795,-0.034447,-0.017225,0.009173,-0.047709,-0.086404,-0.027296,0.056134,-0.008841,-0.019224,...,0.014499,-0.017467,0.069493,-0.043728,-0.061131,-0.034409,-0.019209,-0.063518,0.046065,-0.051414
77,sequence_40866,-0.035596,-0.016456,0.009347,-0.047927,-0.086399,-0.027237,0.055878,-0.008903,-0.019285,...,0.014188,-0.017425,0.069981,-0.043095,-0.062113,-0.034967,-0.019173,-0.063540,0.045297,-0.051609
78,sequence_40799,-0.035178,-0.016525,0.009452,-0.048335,-0.086450,-0.027318,0.055956,-0.009279,-0.019166,...,0.014311,-0.016970,0.069754,-0.043439,-0.061552,-0.034948,-0.019363,-0.063249,0.045544,-0.051492
79,sequence_40788,-0.035108,-0.016591,0.009429,-0.047655,-0.086538,-0.026997,0.055905,-0.009023,-0.019254,...,0.013989,-0.017033,0.069559,-0.043302,-0.061736,-0.034729,-0.019668,-0.063561,0.045360,-0.051291
80,sequence_40867,-0.035632,-0.016472,0.009567,-0.048485,-0.086406,-0.027519,0.056187,-0.008907,-0.019173,...,0.014205,-0.017121,0.069999,-0.043146,-0.061934,-0.035168,-0.019166,-0.063469,0.045154,-0.051445