In [1]:
import sys
sys.path.insert(0, '../src')
import pandas as pd

In [2]:
from numerical_representation.physicochemical_properties import Physicochemical

In [3]:
df = pd.read_csv("../data/absortion.csv")
df

                id  target                                           sequence
0   sequence_40826     539  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
1   sequence_40787     510  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
2   sequence_40789     510  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
3   sequence_40794     519  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
4   sequence_40806     525  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
..             ...     ...                                                ...
76  sequence_40795     562  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
77  sequence_40866     620  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
78  sequence_40799     597  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
79  sequence_40788     510  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...
80  sequence_40867     622  MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...

[81 rows x 3 columns]

## Numerical Representation

In [4]:
physicochemical = Physicochemical(df, "Group_0", "../input_encoders/clustering_encoders.csv", "sequence", "id")
df_physicochemical = physicochemical.encode_dataset()
df_physicochemical

,id,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_288,p_289,p_290,p_291,p_292,p_293,p_294,p_295,p_296,p_297
0,sequence_40826,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
1,sequence_40787,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
2,sequence_40789,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
3,sequence_40794,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
4,sequence_40806,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,sequence_40795,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
77,sequence_40866,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
78,sequence_40799,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
79,sequence_40788,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739
80,sequence_40867,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,290.40675,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739

## Numerical Sequence similarity network

In [5]:
from sequence_similarity_network.network_clustering import NSSN

In [6]:
network = NSSN(df_physicochemical, "percentile", .1, "upper")
modularity_value, dataset = network.get_community_clustering()
dataset

,id,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_289,p_290,p_291,p_292,p_293,p_294,p_295,p_296,p_297,cluster
0,sequence_40826,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,1.0
1,sequence_40787,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,0.0
2,sequence_40789,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,1.0
3,sequence_40794,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,1.0
4,sequence_40806,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,sequence_40795,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,1.0
77,sequence_40866,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,0.0
78,sequence_40799,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,1.0
79,sequence_40788,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,1.0
80,sequence_40867,21.944601,-91.117252,21.944601,-252.509397,150.752932,88.029405,-314.201739,-314.201739,290.40675,...,-38.377385,195.599646,-314.201739,-104.495222,-104.495222,-314.201739,-91.117252,-34.080828,-314.201739,0.0

In [7]:
modularity_value

0.013

## Phylogenetic sequence similary network

In [8]:
from sequence_similarity_network.network_clustering import SSN

In [9]:
network = SSN(df, "percentile", .1, "lower")
modularity_value, dataset = network.get_community_clustering()
dataset

,id,target,sequence,cluster
0,sequence_40826,539,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,0.0
1,sequence_40787,510,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,1.0
2,sequence_40789,510,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,1.0
3,sequence_40794,519,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,1.0
4,sequence_40806,525,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,1.0
...,...,...,...,...
76,sequence_40795,562,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,0.0
77,sequence_40866,620,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,0.0
78,sequence_40799,597,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,0.0
79,sequence_40788,510,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,0.0
80,sequence_40867,622,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,0.0

In [10]:
modularity_value

0.091